# Generated by Django 5.2 on 2025-04-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tile',
            new_name='title',
        ),
    ]
