# Generated by Django 5.2 on 2025-04-30 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_author_user_subscriptions'),
        ('main', '0002_rename_tile_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='main.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
