# Generated by Django 5.2 on 2025-04-30 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_author_alter_user_subscriptions'),
        ('main', '0002_rename_tile_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, through='main.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
